name: Validate Justfiles
permissions:
  contents: read

on:
  pull_request:
    paths:
      - "Justfile"
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v5

      - name: Install just
        uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6 # v2

      - name: Validate Justfiles
        shell: bash
        run: |
          set -xeuo pipefail

          echo "::group:: Validating Justfile"
          just --unstable --fmt --check -f Justfile
          echo "::endgroup::"

          echo "All justfiles are valid"
