---
name: Validate Justfiles

on:
  pull_request:
    paths:
      - "Justfile"

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install just
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4

      - name: Validate Justfiles
        shell: bash
        run: |
          set -xeuo pipefail

          echo "::group:: Validating Justfile"
          just --unstable --fmt --check -f Justfile
          echo "::endgroup::"

          echo "All justfiles are valid"
